<?php

return [
    'dashboard.view' => ['label' => 'Dashboard'],
    'orders.view' => ['label' => 'View orders'],
    'orders.create' => ['label' => 'Create orders'],
    'orders.edit' => ['label' => 'Edit orders'],
    'orders.delete' => ['label' => 'Delete orders'],
    'orders.prepare' => ['label' => 'Prepare orders'],
    'orders.consumption.adjust' => ['label' => 'Request consumption correction'],
    'orders.consumption.review' => ['label' => 'Approve/reject consumption corrections'],
    'customers.view' => ['label' => 'View customers'],
    'customers.create' => ['label' => 'Create customers'],
    'customers.edit' => ['label' => 'Edit customers'],
    'customers.notes' => ['label' => 'Add/edit customer notes'],
    'customers.delete' => ['label' => 'Archive customers'],
    'inventory.view' => ['label' => 'View inventory quantities'],
    'inventory.manage' => ['label' => 'Manage inventory'],
    'inventory.count' => ['label' => 'Perform stock counts'],
    'inventory.request' => ['label' => 'Request stock'],
    'purchases.view' => ['label' => 'View purchases'],
    'purchases.manage' => ['label' => 'Manage purchases'],
    'sales.view' => ['label' => 'View sales'],
    'sales.manage' => ['label' => 'Manage sales'],
    'finance.view' => ['label' => 'View financials'],
    'expenses.manage' => ['label' => 'Manage expenses'],
    'expenses.create' => ['label' => 'Create expenses'],
    'products.view' => ['label' => 'View products'],
    'products.manage' => ['label' => 'Manage products'],
    'manufacturing.view' => ['label' => 'View manufacturing'],
    'manufacturing.manage' => ['label' => 'Manage manufacturing'],
    'reports.view' => ['label' => 'View reports'],
    'users.manage' => ['label' => 'Manage users'],
    'audit.view' => ['label' => 'View audit log'],
    'assets.manage' => ['label' => 'Manage fixed assets'],
    'settings.manage' => ['label' => 'Manage settings'],
];
