<?php

require __DIR__ . '/vendor/autoload.php';
$app = require __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(\Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

DB::transaction(function () {
    DB::table('materials')->where('id', 1)->update(['current_stock' => 1000.0000, 'avg_unit_cost' => 0.3600, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 7)->update(['current_stock' => 87.0000, 'avg_unit_cost' => 21.6783, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 8)->update(['current_stock' => 18.0000, 'avg_unit_cost' => 11.8735, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 9)->update(['current_stock' => 69.0000, 'avg_unit_cost' => 17.3426, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 10)->update(['current_stock' => 99.0000, 'avg_unit_cost' => 10.4800, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 11)->update(['current_stock' => 95.0000, 'avg_unit_cost' => 20.1900, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 12)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 7.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 13)->update(['current_stock' => 385.0000, 'avg_unit_cost' => 9.6700, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 14)->update(['current_stock' => 55.0000, 'avg_unit_cost' => 7.1400, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 15)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 12.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 16)->update(['current_stock' => 110.0000, 'avg_unit_cost' => 7.0100, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 17)->update(['current_stock' => 165.0000, 'avg_unit_cost' => 16.8000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 18)->update(['current_stock' => 130.0000, 'avg_unit_cost' => 13.7300, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 19)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 8.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 20)->update(['current_stock' => 63.0000, 'avg_unit_cost' => 17.5000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 21)->update(['current_stock' => 99.0000, 'avg_unit_cost' => 17.5000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 22)->update(['current_stock' => 70.0000, 'avg_unit_cost' => 10.1300, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 23)->update(['current_stock' => 92.0000, 'avg_unit_cost' => 17.5000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 24)->update(['current_stock' => 92.0000, 'avg_unit_cost' => 16.2000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 25)->update(['current_stock' => 28.0000, 'avg_unit_cost' => 27.0000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 26)->update(['current_stock' => 52.0000, 'avg_unit_cost' => 16.2000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 27)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 17.5000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 28)->update(['current_stock' => 83.0000, 'avg_unit_cost' => 17.5000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 29)->update(['current_stock' => 80.0000, 'avg_unit_cost' => 29.7000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 30)->update(['current_stock' => 86.0000, 'avg_unit_cost' => 20.2500, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 31)->update(['current_stock' => 81.0000, 'avg_unit_cost' => 17.5000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 32)->update(['current_stock' => 75.0000, 'avg_unit_cost' => 11.5000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 33)->update(['current_stock' => 122.0000, 'avg_unit_cost' => 18.0000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 34)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 16.2000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 35)->update(['current_stock' => 97.0000, 'avg_unit_cost' => 12.1500, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 36)->update(['current_stock' => 60.0000, 'avg_unit_cost' => 25.2600, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 37)->update(['current_stock' => 96.0000, 'avg_unit_cost' => 15.5300, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 38)->update(['current_stock' => 42.0000, 'avg_unit_cost' => 18.9000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 39)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 18.9000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 40)->update(['current_stock' => 29.0000, 'avg_unit_cost' => 13.5000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 41)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 6.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 42)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 6.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 43)->update(['current_stock' => 80.0000, 'avg_unit_cost' => 9.6000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 44)->update(['current_stock' => 118.0000, 'avg_unit_cost' => 9.3000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 45)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 8.9100, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 46)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 8.9100, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 47)->update(['current_stock' => 75.0000, 'avg_unit_cost' => 11.8800, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 48)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 8.9100, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 49)->update(['current_stock' => 44.0000, 'avg_unit_cost' => 8.9100, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 50)->update(['current_stock' => 42.0000, 'avg_unit_cost' => 7.3000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 51)->update(['current_stock' => 37.0000, 'avg_unit_cost' => 10.1300, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 52)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 7.0200, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 53)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 10.5300, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 54)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 15.1200, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 55)->update(['current_stock' => 65.0000, 'avg_unit_cost' => 10.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 56)->update(['current_stock' => 70.0000, 'avg_unit_cost' => 11.5000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 57)->update(['current_stock' => 99.0000, 'avg_unit_cost' => 7.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 58)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 16.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 59)->update(['current_stock' => 90.0000, 'avg_unit_cost' => 9.8000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 60)->update(['current_stock' => 150.0000, 'avg_unit_cost' => 12.4200, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 61)->update(['current_stock' => 63.0000, 'avg_unit_cost' => 9.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 62)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 8.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 63)->update(['current_stock' => 68.0000, 'avg_unit_cost' => 15.5500, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 64)->update(['current_stock' => 96.0000, 'avg_unit_cost' => 13.1000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 65)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 10.1500, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 66)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 11.5000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 67)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 9.5000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 68)->update(['current_stock' => 77.0000, 'avg_unit_cost' => 15.5500, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 69)->update(['current_stock' => 83.0000, 'avg_unit_cost' => 13.2000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 70)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 9.7200, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 71)->update(['current_stock' => 84.0000, 'avg_unit_cost' => 20.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 72)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 11.2000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 73)->update(['current_stock' => 69.0000, 'avg_unit_cost' => 13.1000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 74)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 17.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 75)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 6.5000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 76)->update(['current_stock' => 88.0000, 'avg_unit_cost' => 9.2000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 77)->update(['current_stock' => 25.0000, 'avg_unit_cost' => 8.9000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 78)->update(['current_stock' => 5.0000, 'avg_unit_cost' => 10.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 79)->update(['current_stock' => 45.0000, 'avg_unit_cost' => 5.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 80)->update(['current_stock' => 0.0000, 'avg_unit_cost' => 0.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 81)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 15.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 82)->update(['current_stock' => 38.0000, 'avg_unit_cost' => 40.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 83)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 7.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 84)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 11.6000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 85)->update(['current_stock' => 45.0000, 'avg_unit_cost' => 11.6000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 86)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 21.2000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 87)->update(['current_stock' => 20.0000, 'avg_unit_cost' => 12.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 88)->update(['current_stock' => 87.0000, 'avg_unit_cost' => 10.8000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 89)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 11.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 90)->update(['current_stock' => 90.0000, 'avg_unit_cost' => 8.8000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 91)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 11.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 92)->update(['current_stock' => 42.0000, 'avg_unit_cost' => 7.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 93)->update(['current_stock' => 75.0000, 'avg_unit_cost' => 8.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 94)->update(['current_stock' => 100.0000, 'avg_unit_cost' => 13.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 95)->update(['current_stock' => 47.0000, 'avg_unit_cost' => 6.4000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 96)->update(['current_stock' => 77.0000, 'avg_unit_cost' => 19.2000, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 97)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 12.0500, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 98)->update(['current_stock' => 45.0000, 'avg_unit_cost' => 12.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 99)->update(['current_stock' => 42.0000, 'avg_unit_cost' => 5.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 100)->update(['current_stock' => 48.0000, 'avg_unit_cost' => 13.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 101)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 8.6000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 102)->update(['current_stock' => 12.0000, 'avg_unit_cost' => 12.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 103)->update(['current_stock' => 11.0000, 'avg_unit_cost' => 10.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 104)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 6.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 105)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 19.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 106)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 22.4500, 'supplier_name' => 'الغبرة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 107)->update(['current_stock' => 50.0000, 'avg_unit_cost' => 9.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 108)->update(['current_stock' => 8.0000, 'avg_unit_cost' => 370.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 109)->update(['current_stock' => 24.0000, 'avg_unit_cost' => 11.7500, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 110)->update(['current_stock' => 1.0000, 'avg_unit_cost' => 880.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 111)->update(['current_stock' => 1.0000, 'avg_unit_cost' => 810.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 112)->update(['current_stock' => 3.0000, 'avg_unit_cost' => 135.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 113)->update(['current_stock' => 4.0000, 'avg_unit_cost' => 54.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 114)->update(['current_stock' => 8.0000, 'avg_unit_cost' => 40.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 115)->update(['current_stock' => 43.0000, 'avg_unit_cost' => 9.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 116)->update(['current_stock' => 6.0000, 'avg_unit_cost' => 79.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 117)->update(['current_stock' => 3.0000, 'avg_unit_cost' => 3.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 118)->update(['current_stock' => 1.0000, 'avg_unit_cost' => 1.0000, 'supplier_name' => 'أهل الثقة', 'updated_at' => now()]);
    DB::table('materials')->where('id', 119)->update(['current_stock' => 164.0000, 'avg_unit_cost' => 12.0500, 'supplier_name' => 'بحر', 'updated_at' => now()]);
    DB::table('materials')->where('id', 120)->update(['current_stock' => 420.0000, 'avg_unit_cost' => 90.0000, 'supplier_name' => 'بحر / غير معروف', 'updated_at' => now()]);
    DB::table('materials')->where('id', 121)->update(['current_stock' => 390.0000, 'avg_unit_cost' => 65.0000, 'supplier_name' => null, 'updated_at' => now()]);
    DB::table('materials')->where('id', 122)->update(['current_stock' => 431.0000, 'avg_unit_cost' => 35.0000, 'supplier_name' => null, 'updated_at' => now()]);
});

echo 'Materials: '.DB::table('materials')->count().PHP_EOL;
echo 'Current stock sum: '.DB::table('materials')->sum('current_stock').PHP_EOL;
