import { useCallback } from 'react';
import { useAppDispatch, useAppSelector } from '@/store';
import { languageSliceName, setLang } from '@/store/slices/languageSlice';

type Lang = 'ar' | 'en';

interface Translations {
  [key: string]: { ar: string; en: string };
}

const translations: Translations = {
  brand: { ar: 'روح', en: 'Rouh' },
  home: { ar: 'الرئيسية', en: 'Home' },
  shop: { ar: 'المتجر', en: 'Shop' },
  about: { ar: 'من نحن', en: 'About Us' },
  contact: { ar: 'تواصل معنا', en: 'Contact' },
  cart: { ar: 'السلة', en: 'Cart' },
  search: { ar: 'بحث...', en: 'Search...' },
  addToCart: { ar: 'أضف إلى السلة', en: 'Add to Cart' },
  buyWhatsApp: { ar: 'اشتر عبر واتساب', en: 'Buy via WhatsApp' },
  featured: { ar: 'المميزة', en: 'Featured' },
  newArrivals: { ar: 'وصل حديثاً', en: 'New Arrivals' },
  bestSellers: { ar: 'الأكثر مبيعاً', en: 'Best Sellers' },
  heroTitle: { ar: 'اكتشف عطرك المثالي', en: 'Discover Your Perfect Scent' },
  heroSubtitle: { ar: 'عطور فاخرة تعكس أناقتك وتميزك', en: 'Luxury fragrances that reflect your elegance' },
  shopNow: { ar: 'تسوق الآن', en: 'Shop Now' },
  price: { ar: 'السعر', en: 'Price' },
  category: { ar: 'التصنيف', en: 'Category' },
  allCategories: { ar: 'جميع التصنيفات', en: 'All Categories' },
  men: { ar: 'رجالي', en: 'Men' },
  women: { ar: 'نسائي', en: 'Women' },
  unisex: { ar: 'للجنسين', en: 'Unisex' },
  oud: { ar: 'عود', en: 'Oud' },
  floral: { ar: 'زهري', en: 'Floral' },
  woody: { ar: 'خشبي', en: 'Woody' },
  fresh: { ar: 'منعش', en: 'Fresh' },
  oriental: { ar: 'شرقي', en: 'Oriental' },
  filter: { ar: 'تصفية', en: 'Filter' },
  sortBy: { ar: 'ترتيب حسب', en: 'Sort By' },
  priceLowHigh: { ar: 'السعر: الأقل أولاً', en: 'Price: Low to High' },
  priceHighLow: { ar: 'السعر: الأعلى أولاً', en: 'Price: High to Low' },
  newest: { ar: 'الأحدث', en: 'Newest' },
  removeFromCart: { ar: 'إزالة', en: 'Remove' },
  checkout: { ar: 'إتمام الشراء', en: 'Checkout' },
  total: { ar: 'المجموع', en: 'Total' },
  quantity: { ar: 'الكمية', en: 'Quantity' },
  emptyCart: { ar: 'سلة التسوق فارغة', en: 'Your cart is empty' },
  continueShopping: { ar: 'متابعة التسوق', en: 'Continue Shopping' },
  aboutTitle: { ar: 'عن روح', en: 'About Rouh' },
  aboutText: { ar: 'روح هي علامة تجارية سورية فاخرة للعطور، نقدم أرقى العطور الشرقية والغربية التي تعكس الأصالة والحداثة.', en: 'Rouh is a premium Syrian perfume brand, offering the finest oriental and western fragrances that reflect authenticity and modernity.' },
  contactTitle: { ar: 'تواصل معنا', en: 'Get in Touch' },
  name: { ar: 'الاسم', en: 'Name' },
  email: { ar: 'البريد الإلكتروني', en: 'Email' },
  message: { ar: 'الرسالة', en: 'Message' },
  send: { ar: 'إرسال', en: 'Send' },
  phone: { ar: 'الهاتف', en: 'Phone' },
  address: { ar: 'العنوان', en: 'Address' },
  followUs: { ar: 'تابعنا', en: 'Follow Us' },
  rights: { ar: 'جميع الحقوق محفوظة', en: 'All Rights Reserved' },
  description: { ar: 'الوصف', en: 'Description' },
  details: { ar: 'التفاصيل', en: 'Details' },
  relatedProducts: { ar: 'منتجات ذات صلة', en: 'Related Products' },
  size: { ar: 'الحجم', en: 'Size' },
  customerDetails: { ar: 'بيانات العميل', en: 'Customer Details' },
  deliveryAddress: { ar: 'عنوان التوصيل', en: 'Delivery Address' },
  city: { ar: 'المدينة', en: 'City' },
  paymentMethod: { ar: 'طريقة الدفع', en: 'Payment Method' },
  cashOnDelivery: { ar: 'الدفع عند الاستلام', en: 'Cash on Delivery' },
  placeOrder: { ar: 'تأكيد الطلب', en: 'Place Order' },
  subtotal: { ar: 'المجموع الفرعي', en: 'Subtotal' },
  shipping: { ar: 'الشحن', en: 'Shipping' },
  orderSummary: { ar: 'ملخص الطلب', en: 'Order Summary' },
  ourStory: { ar: 'قصتنا', en: 'Our Story' },
  ourVision: { ar: 'رؤيتنا', en: 'Our Vision' },
  ourMission: { ar: 'مهمتنا', en: 'Our Mission' },
  freeShipping: { ar: 'شحن مجاني', en: 'Free Shipping' },
  freeShippingDesc: { ar: 'على الطلبات فوق ٥٠,٠٠٠ ل.س', en: 'On orders over 50,000 SYP' },
  premiumQuality: { ar: 'جودة فائقة', en: 'Premium Quality' },
  premiumQualityDesc: { ar: 'عطور أصلية ١٠٠٪', en: '100% Authentic Perfumes' },
  support: { ar: 'دعم ٢٤/٧', en: '24/7 Support' },
  supportDesc: { ar: 'نحن هنا لمساعدتك', en: "We're here to help" },
  collections: { ar: 'المجموعات', en: 'Collections' },
  exploreCollection: { ar: 'استكشف المجموعة', en: 'Explore Collection' },
  login: { ar: 'تسجيل الدخول', en: 'Sign In' },
  signup: { ar: 'إنشاء حساب', en: 'Sign Up' },
  logout: { ar: 'تسجيل الخروج', en: 'Sign Out' },
  adminPanel: { ar: 'لوحة التحكم', en: 'Admin Panel' },
  wishlist: { ar: 'المفضلة', en: 'Wishlist' },
  addToWishlist: { ar: 'أضف للمفضلة', en: 'Add to wishlist' },
  removeFromWishlist: { ar: 'إزالة من المفضلة', en: 'Remove from wishlist' },
  addedToWishlist: { ar: 'تمت الإضافة للمفضلة', en: 'Added to wishlist' },
  removedFromWishlist: { ar: 'تمت الإزالة من المفضلة', en: 'Removed from wishlist' },
  recentlyViewed: { ar: 'شاهدتها مؤخراً', en: 'Recently Viewed' },
  reviews: { ar: 'التقييمات', en: 'Reviews' },
  writeReview: { ar: 'اكتب تقييمك', en: 'Write a Review' },
  yourRating: { ar: 'تقييمك', en: 'Your Rating' },
  yourComment: { ar: 'تعليقك (اختياري)', en: 'Your comment (optional)' },
  submitReview: { ar: 'إرسال التقييم', en: 'Submit Review' },
  noReviewsYet: { ar: 'لا توجد تقييمات بعد. كن أول من يقيّم!', en: 'No reviews yet. Be the first to review!' },
  loginToReview: { ar: 'سجّل الدخول لكتابة تقييم', en: 'Sign in to write a review' },
  reviewThanks: { ar: 'شكراً لتقييمك!', en: 'Thanks for your review!' },
  averageRating: { ar: 'متوسط التقييم', en: 'Average Rating' },
  lowStock: { ar: 'كمية محدودة', en: 'Low stock' },
  outOfStock: { ar: 'نفد المخزون', en: 'Out of stock' },
  inStock: { ar: 'متوفر', en: 'In stock' },
  onlyXLeft: { ar: 'متبقي فقط', en: 'Only left' },
  trackOrder: { ar: 'تتبع الطلب', en: 'Track Order' },
  trackOrderTitle: { ar: 'تتبع طلبك', en: 'Track Your Order' },
  enterPhone: { ar: 'أدخل رقم هاتفك', en: 'Enter your phone number' },
  trackBtn: { ar: 'بحث', en: 'Search' },
  noOrdersFound: { ar: 'لم نجد أي طلبات بهذا الرقم', en: 'No orders found with this phone number' },
  orderNumber: { ar: 'رقم الطلب', en: 'Order #' },
  orderStatus: { ar: 'حالة الطلب', en: 'Status' },
  orderDate: { ar: 'تاريخ الطلب', en: 'Order Date' },
  couponCode: { ar: 'كود الخصم', en: 'Coupon Code' },
  applyCoupon: { ar: 'تطبيق', en: 'Apply' },
  couponApplied: { ar: 'تم تطبيق الكوبون', en: 'Coupon applied' },
  invalidCoupon: { ar: 'كود غير صالح أو منتهي', en: 'Invalid or expired coupon' },
  discount: { ar: 'الخصم', en: 'Discount' },
  removeCoupon: { ar: 'إزالة', en: 'Remove' },
  totalRevenue: { ar: 'إجمالي المبيعات', en: 'Total Revenue' },
  avgOrder: { ar: 'متوسط الطلب', en: 'Avg Order' },
  last30Days: { ar: 'آخر ٣٠ يوم', en: 'Last 30 days' },
  salesChart: { ar: 'المبيعات اليومية', en: 'Daily Sales' },
  topProducts: { ar: 'أكثر المنتجات مبيعاً', en: 'Top Products' },
  lowStockAlert: { ar: 'تنبيه: مخزون منخفض', en: 'Low Stock Alert' },
  exportCsv: { ar: 'تصدير Excel', en: 'Export CSV' },
  printInvoice: { ar: 'طباعة الفاتورة', en: 'Print Invoice' },
  noSales: { ar: 'لا مبيعات بعد', en: 'No sales yet' },
  filterByStatus: { ar: 'تصفية بالحالة', en: 'Filter by status' },
  all: { ar: 'الكل', en: 'All' },
  units: { ar: 'وحدة', en: 'units' },
  compare: { ar: 'مقارنة', en: 'Compare' },
  compareProducts: { ar: 'مقارنة المنتجات', en: 'Compare Products' },
  addToCompare: { ar: 'أضف للمقارنة', en: 'Add to compare' },
  removeFromCompare: { ar: 'إزالة من المقارنة', en: 'Remove from compare' },
  addedToCompare: { ar: 'تمت الإضافة للمقارنة', en: 'Added to comparison' },
  removedFromCompare: { ar: 'تمت الإزالة من المقارنة', en: 'Removed from comparison' },
  noProductsToCompare: { ar: 'لا توجد منتجات للمقارنة', en: 'No products to compare' },
  maxCompareLimit: { ar: 'يمكنك مقارنة 4 منتجات كحد أقصى', en: 'You can compare up to 4 products' },
  fragrance: { ar: 'العائلة العطرية', en: 'Fragrance Family' },
  availableSizes: { ar: 'الأحجام المتاحة', en: 'Available Sizes' },
  actions: { ar: 'إجراءات', en: 'Actions' },
  viewDetails: { ar: 'عرض التفاصيل', en: 'View Details' },
  clearAll: { ar: 'مسح الكل', en: 'Clear All' },
  optional: { ar: 'اختياري', en: 'Optional' },
};

export const useLanguage = () => {
  const dispatch = useAppDispatch();
  const language = useAppSelector((state) => state[languageSliceName]);

  const t = useCallback(
    (key: string) => translations[key]?.[language.lang] || key,
    [language.lang]
  );

  const setLanguage = useCallback(
    (newLang: Lang) => dispatch(setLang(newLang)),
    [dispatch]
  );

  return {
    lang: language.lang,
    setLang: setLanguage,
    t,
    dir: language.dir,
  };
};
